
import __ASTRO_IMAGE_IMPORT_ZWgIyp from "../../../images/work/awqat/0.1.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fawqat.mdx";
import __ASTRO_IMAGE_IMPORT_ZNYS65 from "../../../images/work/earthmosque/1.2.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fearth-mosque-no-1.mdx";
import __ASTRO_IMAGE_IMPORT_Z11xTJd from "../../../images/work/bamyan/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fbamyan.mdx";
import __ASTRO_IMAGE_IMPORT_2ooyjD from "../../../images/work/foa/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fflagsofafghanistan.mdx";
import __ASTRO_IMAGE_IMPORT_ZAlHrv from "../../../images/work/jainamaaz/0.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fjainamaaz.mdx";
import __ASTRO_IMAGE_IMPORT_fAorz from "../../../images/work/millie/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fmillie-rail.mdx";
import __ASTRO_IMAGE_IMPORT_1nQFVK from "../../../images/work/senj/0.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fsenj.mdx";
import __ASTRO_IMAGE_IMPORT_wYARE from "../../../images/work/sfoic/1.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fsfoic.mdx";
import __ASTRO_IMAGE_IMPORT_Z1QFnyf from "../../../images/work/theamericanmosque/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Ftheamericanmosque.mdx";
export default new Map([["../../../images/work/awqat/0.1.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fawqat.mdx", __ASTRO_IMAGE_IMPORT_ZWgIyp], ["../../../images/work/earthmosque/1.2.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fearth-mosque-no-1.mdx", __ASTRO_IMAGE_IMPORT_ZNYS65], ["../../../images/work/bamyan/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fbamyan.mdx", __ASTRO_IMAGE_IMPORT_Z11xTJd], ["../../../images/work/foa/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fflagsofafghanistan.mdx", __ASTRO_IMAGE_IMPORT_2ooyjD], ["../../../images/work/jainamaaz/0.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fjainamaaz.mdx", __ASTRO_IMAGE_IMPORT_ZAlHrv], ["../../../images/work/millie/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fmillie-rail.mdx", __ASTRO_IMAGE_IMPORT_fAorz], ["../../../images/work/senj/0.jpg?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fsenj.mdx", __ASTRO_IMAGE_IMPORT_1nQFVK], ["../../../images/work/sfoic/1.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Fsfoic.mdx", __ASTRO_IMAGE_IMPORT_wYARE], ["../../../images/work/theamericanmosque/0.png?astroContentImageFlag=&importer=src%2Fpages%2Fwork%2Fentries%2Ftheamericanmosque.mdx", __ASTRO_IMAGE_IMPORT_Z1QFnyf]]);
		